services:
  - type: web
    name: ivory-blog
    env: python
    region: frankfurt
    plan: free

    buildCommand: "./build.sh"
    startCommand: "gunicorn ivory_eatery.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false